# -*- mode: ruby -*-
# vi: set ft=ruby :v

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.define "kubemaster", primary: true do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = 'kubemaster'
    master.vm.network :private_network, ip: "192.168.40.200"
    master.vm.provider "virtualbox" do |vbox|
      vbox.memory = 2048
      vbox.cpus = 2
    end
  end
  config.vm.define "kubeworker1", primary: true do |worker1|
    worker1.vm.box = "ubuntu/bionic64"
    worker1.vm.hostname = 'kubeworker1'
    worker1.vm.network :private_network, ip: "192.168.40.201"
    worker1.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 2
    end
  end
  config.vm.define "kubeworker2", primary: true do |worker2|
    worker2.vm.box = "ubuntu/bionic64"
    worker2.vm.hostname = 'kubeworker2'
    worker2.vm.network :private_network, ip: "192.168.40.202"
    worker2.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 2
    end
  end
end